### ISSUE TITLE
Switching ammo types with bolt pouch incorrectly adds value to profit/loss mode, as well as other pouch items. (I.E. Rune Pouch, Essence Pouch, etc.) + Small typo

### ISSUE THREAD

**Issue by RaggzyOSRS** [hybridbrizz/inventorytotal#10]
Title basically explains everything nice and simple, also under the description for "Inventory Offset X Negative", the description mentions y-axis instead of x-axis.

**Comment by erversteeg** [comment]
I'm not sure if there is a way to track bolt pouch and essence pouch but rune pouch is supported.
