### ISSUE TITLE
doesnt ignore worn items when switching

### ISSUE THREAD

**Issue by Deathwish0404** [hybridbrizz/inventorytotal#11]
Since last update to osrs it takes in value of equipment that is used during switches instead of voiding it and giving loot total

**Comment by hybridbrizz** [comment]
Sorry about that. Looks like `player.getPlayerComposition().getEquipmentIds()` is longer a valid way to get equipment ids. I fixed, tested, and pushed an update to Plugin Hub so as soon as they approve it will automatically fix for you.

**Comment by Deathwish0404** [comment]
Thank you, youre the man, love the plugin
