### ISSUE TITLE
Feature Request: A way to control when profit is reset

### ISSUE THREAD

**Issue by Voiture-0** [hybridbrizz/inventorytotal#12]
Right now the profit tracker resets when opening the bank. It would be nice if there was a way to control when you want it to reset or not. Sometimes I need to bank to deposit items, or grab something, but I am still continuing the thing I want to track profit for.

**Comment by Andrez092** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive

**Comment by hybridbrizz** [comment]
Got a keybind added in for manually resetting and made the automatic reset optional so you can disable it. Got the changes pushed to Plugin Hub today so within a week or two that functionality will be available for you.
