### ISSUE TITLE
Plugin randomly stops working

### ISSUE THREAD

**Issue by OzanKurt** [hybridbrizz/inventorytotal#15]
I believe it happens after every game update for a while, can we prevent this somehow?

Yesterday it was above the bag icon, now it's gone.

![image](https://github.com/user-attachments/assets/6df862bc-9989-4842-9f83-cc1023f7b049)

**Comment by hybridbrizz** [comment]
So sorry this is happening. It looks like you are playing on fixed classic. First make sure the plugin version is "19c9a499" in the plugins panel. Inventory total got messed up for fixed classic in the update before this latest one then got fixed. If you reset the plugin and then change the "Inventory Offset Y" value to 42 up from 12 it should be good. You may need to restart once after that.

**Comment by OzanKurt** [comment]
@hybridbrizz Thank you for quick response!

As you mentioned it seems to work on the resizable version.

I tried to re-install and reset the plugin settings but that did not help.

However, restarting client worked.

I believe once you switch to resizable it breaks.

**Comment by hybridbrizz** [comment]
Thanks for the info. I was able to replicate what you are experiencing after switching to the resizable game client. Believe I have fixed it, just need to do some testing and make sure everything is ok. After this new update there shouldn't be any issues with it disappearing when it shouldn't.

**Comment by OzanKurt** [comment]
That's great, thanks!
