### ISSUE TITLE
toggle between total gp and profit/loss mode by shift clicking or control clicking the gp value popup. 

### ISSUE THREAD

**Issue by voguelike** [hybridbrizz/inventorytotal#6]
it would be nice to be able to flip between total gp and the profit/loss mode of the plugin with a quick shift or control click instead of having to go into the plugin menu, finding the plugin and then toggling the option.

**Comment by erversteeg** [comment]
Thanks for the great suggestion! I added this feature in today. It's a hotkey that you can set to whatever you like. The change should be live in a few days.
